//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PsychologyTheory", Namespace="http://schemas.datacontract.org/2004/07/SPHSS_SOAP_APIService.SoapModels")]
    public partial class PsychologyTheory : object
    {
        
        private string ApplicationField;
        
        private string AuthorField;
        
        private System.Nullable<System.DateTime> CreateAtField;
        
        private string CriticismField;
        
        private string DescriptionField;
        
        private int IdField;
        
        private string NameField;
        
        private string PrincipleField;
        
        private string RelatedTheoryField;
        
        private string TheoryTypeField;
        
        private SOAPServiceReference.Topic TopicField;
        
        private int TopicIdField;
        
        private System.Nullable<System.DateTime> UpdateAtField;
        
        private System.Nullable<int> YearPublishedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Application
        {
            get
            {
                return this.ApplicationField;
            }
            set
            {
                this.ApplicationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author
        {
            get
            {
                return this.AuthorField;
            }
            set
            {
                this.AuthorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateAt
        {
            get
            {
                return this.CreateAtField;
            }
            set
            {
                this.CreateAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Criticism
        {
            get
            {
                return this.CriticismField;
            }
            set
            {
                this.CriticismField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Principle
        {
            get
            {
                return this.PrincipleField;
            }
            set
            {
                this.PrincipleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelatedTheory
        {
            get
            {
                return this.RelatedTheoryField;
            }
            set
            {
                this.RelatedTheoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TheoryType
        {
            get
            {
                return this.TheoryTypeField;
            }
            set
            {
                this.TheoryTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPServiceReference.Topic Topic
        {
            get
            {
                return this.TopicField;
            }
            set
            {
                this.TopicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TopicId
        {
            get
            {
                return this.TopicIdField;
            }
            set
            {
                this.TopicIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateAt
        {
            get
            {
                return this.UpdateAtField;
            }
            set
            {
                this.UpdateAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YearPublished
        {
            get
            {
                return this.YearPublishedField;
            }
            set
            {
                this.YearPublishedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Topic", Namespace="http://schemas.datacontract.org/2004/07/SPHSS_SOAP_APIService.SoapModels")]
    public partial class Topic : object
    {
        
        private System.Nullable<System.DateTime> CreateAtField;
        
        private string DescriptionField;
        
        private int IdField;
        
        private string NameField;
        
        private System.Nullable<System.DateTime> UpdateAtField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateAt
        {
            get
            {
                return this.CreateAtField;
            }
            set
            {
                this.CreateAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateAt
        {
            get
            {
                return this.UpdateAtField;
            }
            set
            {
                this.UpdateAtField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPServiceReference.IPsychologyTheorySoapService")]
    public interface IPsychologyTheorySoapService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPsychologyTheorySoapService/GetPsychologyTheories", ReplyAction="http://tempuri.org/IPsychologyTheorySoapService/GetPsychologyTheoriesResponse")]
        System.Threading.Tasks.Task<SOAPServiceReference.PsychologyTheory[]> GetPsychologyTheoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPsychologyTheorySoapService/GetPsychologyTheory", ReplyAction="http://tempuri.org/IPsychologyTheorySoapService/GetPsychologyTheoryResponse")]
        System.Threading.Tasks.Task<SOAPServiceReference.PsychologyTheory> GetPsychologyTheoryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPsychologyTheorySoapService/CreatePsychologyTheory", ReplyAction="http://tempuri.org/IPsychologyTheorySoapService/CreatePsychologyTheoryResponse")]
        System.Threading.Tasks.Task<int> CreatePsychologyTheoryAsync(SOAPServiceReference.PsychologyTheory psychologyTheory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPsychologyTheorySoapService/UpdatePsychologyTheory", ReplyAction="http://tempuri.org/IPsychologyTheorySoapService/UpdatePsychologyTheoryResponse")]
        System.Threading.Tasks.Task<int> UpdatePsychologyTheoryAsync(SOAPServiceReference.PsychologyTheory psychologyTheory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPsychologyTheorySoapService/DeletePsychologyTheory", ReplyAction="http://tempuri.org/IPsychologyTheorySoapService/DeletePsychologyTheoryResponse")]
        System.Threading.Tasks.Task<bool> DeletePsychologyTheoryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPsychologyTheorySoapService/GetTopics", ReplyAction="http://tempuri.org/IPsychologyTheorySoapService/GetTopicsResponse")]
        System.Threading.Tasks.Task<SOAPServiceReference.Topic[]> GetTopicsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IPsychologyTheorySoapServiceChannel : SOAPServiceReference.IPsychologyTheorySoapService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class PsychologyTheorySoapServiceClient : System.ServiceModel.ClientBase<SOAPServiceReference.IPsychologyTheorySoapService>, SOAPServiceReference.IPsychologyTheorySoapService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PsychologyTheorySoapServiceClient() : 
                base(PsychologyTheorySoapServiceClient.GetDefaultBinding(), PsychologyTheorySoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPsychologyTheorySoapService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PsychologyTheorySoapServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PsychologyTheorySoapServiceClient.GetBindingForEndpoint(endpointConfiguration), PsychologyTheorySoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PsychologyTheorySoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PsychologyTheorySoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PsychologyTheorySoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PsychologyTheorySoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PsychologyTheorySoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SOAPServiceReference.PsychologyTheory[]> GetPsychologyTheoriesAsync()
        {
            return base.Channel.GetPsychologyTheoriesAsync();
        }
        
        public System.Threading.Tasks.Task<SOAPServiceReference.PsychologyTheory> GetPsychologyTheoryAsync(int id)
        {
            return base.Channel.GetPsychologyTheoryAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> CreatePsychologyTheoryAsync(SOAPServiceReference.PsychologyTheory psychologyTheory)
        {
            return base.Channel.CreatePsychologyTheoryAsync(psychologyTheory);
        }
        
        public System.Threading.Tasks.Task<int> UpdatePsychologyTheoryAsync(SOAPServiceReference.PsychologyTheory psychologyTheory)
        {
            return base.Channel.UpdatePsychologyTheoryAsync(psychologyTheory);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePsychologyTheoryAsync(int id)
        {
            return base.Channel.DeletePsychologyTheoryAsync(id);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceReference.Topic[]> GetTopicsAsync()
        {
            return base.Channel.GetTopicsAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPsychologyTheorySoapService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPsychologyTheorySoapService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7110/SPHSSSoapService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PsychologyTheorySoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPsychologyTheorySoapService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PsychologyTheorySoapServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPsychologyTheorySoapService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPsychologyTheorySoapService,
        }
    }
}
